### ISSUE TITLE
Do we need to download the src code from the two referenced repositories?

### ISSUE THREAD

**Issue by quangvnai** [idansc/mrr-ndcg#2]
Hi Schwartz, 

Congratulations on your great work for Visual Dialog. I've been following your research work for a while.
It seems like we just need to download the trained models from 2 repos and run your notebooks directly,  right?

Many thanks for your contribution to the community

**Comment by davidnvq** [comment]
BTW, I'm not sure why you exclude our work from your literature review and comparison. 
Feel free to take a look at our paper and available source code at https://github.com/davidnvq/visdial. 
Thanks.

**Comment by idansc** [comment]
Hi, the ensemble only needs the output scores from FGA and LS models. 
Please note that I have already extracted the output scores for you: [here](https://technionmail-my.sharepoint.com/personal/idansc_campus_technion_ac_il/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fidansc%5Fcampus%5Ftechnion%5Fac%5Fil%2FDocuments%2Fmrr%5Fndcg%2Fmodels&originalPath=aHR0cHM6Ly90ZWNobmlvbm1haWwtbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvaWRhbnNjX2NhbXB1c190ZWNobmlvbl9hY19pbC9FakdEU2JLVHRKSkNqdHdlSXhHM2RVSUJYcTlJWENoQlhyQjNHVlFDeE5EOGh3P3J0aW1lPW8tOVAyTUFRMlVn)

**Comment by quangvnai** [comment]
Thanks @idansc. I did run your notebook perfectly. 
BTW, I'm not sure why you excluded our work from your literature review/comparison. Feel free to take a look at our [code](https://github.com/davidnvq/visdial) here.

**Comment by idansc** [comment]
> Thanks @idansc. I did run your notebook perfectly.
> BTW, I'm not sure why you excluded our work from your literature review/comparison. Feel free to take a look at our [code](https://github.com/davidnvq/visdial) here.

My bad, I will mention your work in the final version

**Comment by quangvnai** [comment]
Thank you for your kind action to ours.
